"""add api resource management.

Revision ID: 418a2649d5e9
Revises: f2c91b5e8a44
Create Date: 2026-08-10 11:56:10.530530
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '418a2649d5e9'
down_revision: str | None = 'f2c91b5e8a44'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_providers',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('provider_type', sa.String(length=32), nullable=False),
    sa.Column('default_base_url', sa.String(length=512), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_providers'))
    )
    op.create_index(op.f('ix_api_providers_is_enabled'), 'api_providers', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_api_providers_slug'), 'api_providers', ['slug'], unique=True)
    op.create_table('api_accounts',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('billing_currency', sa.String(length=16), nullable=True),
    sa.Column('monthly_budget', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_api_accounts_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['api_providers.id'], name=op.f('fk_api_accounts_provider_id_api_providers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_accounts'))
    )
    op.create_index(op.f('ix_api_accounts_created_by_user_id'), 'api_accounts', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_api_accounts_last_synced_at'), 'api_accounts', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_api_accounts_name'), 'api_accounts', ['name'], unique=False)
    op.create_index(op.f('ix_api_accounts_owner'), 'api_accounts', ['owner'], unique=False)
    op.create_index(op.f('ix_api_accounts_provider_id'), 'api_accounts', ['provider_id'], unique=False)
    op.create_index('ix_api_accounts_provider_name_url', 'api_accounts', ['provider_id', 'name', 'base_url'], unique=False)
    op.create_index(op.f('ix_api_accounts_status'), 'api_accounts', ['status'], unique=False)
    op.create_table('api_account_models',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('provider_model_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('model_family', sa.String(length=128), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('context_window', sa.BigInteger(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['api_accounts.id'], name=op.f('fk_api_account_models_account_id_api_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_account_models')),
    sa.UniqueConstraint('account_id', 'provider_model_id', name=op.f('uq_api_account_models_account_id'))
    )
    op.create_index(op.f('ix_api_account_models_account_id'), 'api_account_models', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_account_models_is_available'), 'api_account_models', ['is_available'], unique=False)
    op.create_index(op.f('ix_api_account_models_last_seen_at'), 'api_account_models', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_api_account_models_provider_model_id'), 'api_account_models', ['provider_model_id'], unique=False)
    op.create_table('api_balance_snapshots',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('remaining_credit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['api_accounts.id'], name=op.f('fk_api_balance_snapshots_account_id_api_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_balance_snapshots'))
    )
    op.create_index(op.f('ix_api_balance_snapshots_account_id'), 'api_balance_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_balance_snapshots_collected_at'), 'api_balance_snapshots', ['collected_at'], unique=False)
    op.create_table('api_credentials',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('credential_type', sa.String(length=32), nullable=False),
    sa.Column('encrypted_value', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_version', sa.String(length=32), nullable=False),
    sa.Column('masked_value', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error_message', sa.String(length=512), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['api_accounts.id'], name=op.f('fk_api_credentials_account_id_api_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_api_credentials_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_credentials')),
    sa.UniqueConstraint('account_id', 'fingerprint', name=op.f('uq_api_credentials_account_id'))
    )
    op.create_index(op.f('ix_api_credentials_account_id'), 'api_credentials', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_credentials_created_by_user_id'), 'api_credentials', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_api_credentials_expires_at'), 'api_credentials', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_credentials_fingerprint'), 'api_credentials', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_api_credentials_status'), 'api_credentials', ['status'], unique=False)
    op.create_table('api_sync_runs',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('sync_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['api_accounts.id'], name=op.f('fk_api_sync_runs_account_id_api_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_api_sync_runs_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_sync_runs'))
    )
    op.create_index('ix_api_sync_account_type_status', 'api_sync_runs', ['account_id', 'sync_type', 'status'], unique=False)
    op.create_index(op.f('ix_api_sync_runs_account_id'), 'api_sync_runs', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_sync_runs_requested_by_user_id'), 'api_sync_runs', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_api_sync_runs_status'), 'api_sync_runs', ['status'], unique=False)
    op.create_index(op.f('ix_api_sync_runs_sync_type'), 'api_sync_runs', ['sync_type'], unique=False)
    op.create_table('api_health_checks',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.Uuid(), nullable=True),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['api_accounts.id'], name=op.f('fk_api_health_checks_account_id_api_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_id'], ['api_credentials.id'], name=op.f('fk_api_health_checks_credential_id_api_credentials'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_health_checks'))
    )
    op.create_index(op.f('ix_api_health_checks_account_id'), 'api_health_checks', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_health_checks_check_type'), 'api_health_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_api_health_checks_checked_at'), 'api_health_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_api_health_checks_credential_id'), 'api_health_checks', ['credential_id'], unique=False)
    op.create_index(op.f('ix_api_health_checks_status'), 'api_health_checks', ['status'], unique=False)
    op.create_table('api_usage_snapshots',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.Uuid(), nullable=True),
    sa.Column('provider_model_id', sa.String(length=255), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granularity', sa.String(length=16), nullable=False),
    sa.Column('request_count', sa.BigInteger(), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cached_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('provider_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['api_accounts.id'], name=op.f('fk_api_usage_snapshots_account_id_api_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_id'], ['api_credentials.id'], name=op.f('fk_api_usage_snapshots_credential_id_api_credentials'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_usage_snapshots')),
    sa.UniqueConstraint('account_id', 'provider_record_id', name=op.f('uq_api_usage_snapshots_account_id'))
    )
    op.create_index('ix_api_usage_account_period', 'api_usage_snapshots', ['account_id', 'period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_api_usage_snapshots_account_id'), 'api_usage_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_usage_snapshots_collected_at'), 'api_usage_snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_api_usage_snapshots_credential_id'), 'api_usage_snapshots', ['credential_id'], unique=False)
    op.create_index(op.f('ix_api_usage_snapshots_period_end'), 'api_usage_snapshots', ['period_end'], unique=False)
    op.create_index(op.f('ix_api_usage_snapshots_period_start'), 'api_usage_snapshots', ['period_start'], unique=False)
    op.create_index(op.f('ix_api_usage_snapshots_provider_model_id'), 'api_usage_snapshots', ['provider_model_id'], unique=False)
    op.create_index(op.f('ix_api_usage_snapshots_source'), 'api_usage_snapshots', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_usage_snapshots_source'), table_name='api_usage_snapshots')
    op.drop_index(op.f('ix_api_usage_snapshots_provider_model_id'), table_name='api_usage_snapshots')
    op.drop_index(op.f('ix_api_usage_snapshots_period_start'), table_name='api_usage_snapshots')
    op.drop_index(op.f('ix_api_usage_snapshots_period_end'), table_name='api_usage_snapshots')
    op.drop_index(op.f('ix_api_usage_snapshots_credential_id'), table_name='api_usage_snapshots')
    op.drop_index(op.f('ix_api_usage_snapshots_collected_at'), table_name='api_usage_snapshots')
    op.drop_index(op.f('ix_api_usage_snapshots_account_id'), table_name='api_usage_snapshots')
    op.drop_index('ix_api_usage_account_period', table_name='api_usage_snapshots')
    op.drop_table('api_usage_snapshots')
    op.drop_index(op.f('ix_api_health_checks_status'), table_name='api_health_checks')
    op.drop_index(op.f('ix_api_health_checks_credential_id'), table_name='api_health_checks')
    op.drop_index(op.f('ix_api_health_checks_checked_at'), table_name='api_health_checks')
    op.drop_index(op.f('ix_api_health_checks_check_type'), table_name='api_health_checks')
    op.drop_index(op.f('ix_api_health_checks_account_id'), table_name='api_health_checks')
    op.drop_table('api_health_checks')
    op.drop_index(op.f('ix_api_sync_runs_sync_type'), table_name='api_sync_runs')
    op.drop_index(op.f('ix_api_sync_runs_status'), table_name='api_sync_runs')
    op.drop_index(op.f('ix_api_sync_runs_requested_by_user_id'), table_name='api_sync_runs')
    op.drop_index(op.f('ix_api_sync_runs_account_id'), table_name='api_sync_runs')
    op.drop_index('ix_api_sync_account_type_status', table_name='api_sync_runs')
    op.drop_table('api_sync_runs')
    op.drop_index(op.f('ix_api_credentials_status'), table_name='api_credentials')
    op.drop_index(op.f('ix_api_credentials_fingerprint'), table_name='api_credentials')
    op.drop_index(op.f('ix_api_credentials_expires_at'), table_name='api_credentials')
    op.drop_index(op.f('ix_api_credentials_created_by_user_id'), table_name='api_credentials')
    op.drop_index(op.f('ix_api_credentials_account_id'), table_name='api_credentials')
    op.drop_table('api_credentials')
    op.drop_index(op.f('ix_api_balance_snapshots_collected_at'), table_name='api_balance_snapshots')
    op.drop_index(op.f('ix_api_balance_snapshots_account_id'), table_name='api_balance_snapshots')
    op.drop_table('api_balance_snapshots')
    op.drop_index(op.f('ix_api_account_models_provider_model_id'), table_name='api_account_models')
    op.drop_index(op.f('ix_api_account_models_last_seen_at'), table_name='api_account_models')
    op.drop_index(op.f('ix_api_account_models_is_available'), table_name='api_account_models')
    op.drop_index(op.f('ix_api_account_models_account_id'), table_name='api_account_models')
    op.drop_table('api_account_models')
    op.drop_index(op.f('ix_api_accounts_status'), table_name='api_accounts')
    op.drop_index('ix_api_accounts_provider_name_url', table_name='api_accounts')
    op.drop_index(op.f('ix_api_accounts_provider_id'), table_name='api_accounts')
    op.drop_index(op.f('ix_api_accounts_owner'), table_name='api_accounts')
    op.drop_index(op.f('ix_api_accounts_name'), table_name='api_accounts')
    op.drop_index(op.f('ix_api_accounts_last_synced_at'), table_name='api_accounts')
    op.drop_index(op.f('ix_api_accounts_created_by_user_id'), table_name='api_accounts')
    op.drop_table('api_accounts')
    op.drop_index(op.f('ix_api_providers_slug'), table_name='api_providers')
    op.drop_index(op.f('ix_api_providers_is_enabled'), table_name='api_providers')
    op.drop_table('api_providers')
    # ### end Alembic commands ###
