"""initial schema.

Revision ID: 71ec4261e708
Revises:
Create Date: 2026-08-08 00:01:22.813518
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '71ec4261e708'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('architecture', sa.String(length=128), nullable=True),
    sa.Column('model_type', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('source', 'source_id', name=op.f('uq_models_source'))
    )
    op.create_index(op.f('ix_models_model_type'), 'models', ['model_type'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_table('notifications',
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_level'), 'notifications', ['level'], unique=False)
    op.create_table('servers',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('os', sa.String(length=128), nullable=True),
    sa.Column('kernel', sa.String(length=128), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('memory_total', sa.BigInteger(), nullable=True),
    sa.Column('disk_total', sa.BigInteger(), nullable=True),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers'))
    )
    op.create_index(op.f('ix_servers_last_seen'), 'servers', ['last_seen'], unique=False)
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=True)
    op.create_index(op.f('ix_servers_status'), 'servers', ['status'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_table('gpus',
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('gpu_index', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=128), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('memory_total', sa.BigInteger(), nullable=False),
    sa.Column('driver_version', sa.String(length=64), nullable=True),
    sa.Column('cuda_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_gpus_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gpus')),
    sa.UniqueConstraint('server_id', 'gpu_index', name=op.f('uq_gpus_server_id'))
    )
    op.create_index(op.f('ix_gpus_server_id'), 'gpus', ['server_id'], unique=False)
    op.create_index(op.f('ix_gpus_status'), 'gpus', ['status'], unique=False)
    op.create_index(op.f('ix_gpus_uuid'), 'gpus', ['uuid'], unique=True)
    op.create_table('model_download_tasks',
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('target_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('downloaded_size', sa.BigInteger(), nullable=False),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('speed_bytes_per_second', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_model_download_tasks_model_id_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_model_download_tasks_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_download_tasks'))
    )
    op.create_index(op.f('ix_model_download_tasks_model_id'), 'model_download_tasks', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_download_tasks_server_id'), 'model_download_tasks', ['server_id'], unique=False)
    op.create_index(op.f('ix_model_download_tasks_status'), 'model_download_tasks', ['status'], unique=False)
    op.create_table('model_files',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('quantization', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('revision', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_model_files_model_id_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_model_files_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_files')),
    sa.UniqueConstraint('server_id', 'path', name=op.f('uq_model_files_server_id'))
    )
    op.create_index(op.f('ix_model_files_model_id'), 'model_files', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_files_server_id'), 'model_files', ['server_id'], unique=False)
    op.create_index(op.f('ix_model_files_status'), 'model_files', ['status'], unique=False)
    op.create_table('server_agents',
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_agents_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_agents')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_server_agents_token_hash'))
    )
    op.create_index(op.f('ix_server_agents_last_seen'), 'server_agents', ['last_seen'], unique=False)
    op.create_index(op.f('ix_server_agents_server_id'), 'server_agents', ['server_id'], unique=True)
    op.create_table('server_model_directories',
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_model_directories_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_model_directories')),
    sa.UniqueConstraint('server_id', 'path', name=op.f('uq_server_model_directories_server_id'))
    )
    op.create_index(op.f('ix_server_model_directories_server_id'), 'server_model_directories', ['server_id'], unique=False)
    op.create_table('deployments',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_file_id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('backend', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_file_id'], ['model_files.id'], name=op.f('fk_deployments_model_file_id_model_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_deployments_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments')),
    sa.UniqueConstraint('server_id', 'port', name=op.f('uq_deployments_server_id'))
    )
    op.create_index(op.f('ix_deployments_model_file_id'), 'deployments', ['model_file_id'], unique=False)
    op.create_index(op.f('ix_deployments_name'), 'deployments', ['name'], unique=True)
    op.create_index(op.f('ix_deployments_server_id'), 'deployments', ['server_id'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_table('gpu_metrics',
    sa.Column('gpu_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('utilization', sa.Float(), nullable=True),
    sa.Column('memory_used', sa.BigInteger(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('power_usage', sa.Float(), nullable=True),
    sa.Column('power_limit', sa.Float(), nullable=True),
    sa.Column('fan_speed', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], name=op.f('fk_gpu_metrics_gpu_id_gpus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gpu_metrics'))
    )
    op.create_index(op.f('ix_gpu_metrics_gpu_id'), 'gpu_metrics', ['gpu_id'], unique=False)
    op.create_index('ix_gpu_metrics_gpu_timestamp', 'gpu_metrics', ['gpu_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_gpu_metrics_timestamp'), 'gpu_metrics', ['timestamp'], unique=False)
    op.create_table('api_endpoints',
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_api_endpoints_deployment_id_deployments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_endpoints'))
    )
    op.create_index(op.f('ix_api_endpoints_deployment_id'), 'api_endpoints', ['deployment_id'], unique=True)
    op.create_index(op.f('ix_api_endpoints_model_name'), 'api_endpoints', ['model_name'], unique=False)
    op.create_index(op.f('ix_api_endpoints_status'), 'api_endpoints', ['status'], unique=False)
    op.create_table('deployment_gpus',
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('gpu_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_deployment_gpus_deployment_id_deployments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], name=op.f('fk_deployment_gpus_gpu_id_gpus'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('deployment_id', 'gpu_id', name=op.f('pk_deployment_gpus'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment_gpus')
    op.drop_index(op.f('ix_api_endpoints_status'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_model_name'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_deployment_id'), table_name='api_endpoints')
    op.drop_table('api_endpoints')
    op.drop_index(op.f('ix_gpu_metrics_timestamp'), table_name='gpu_metrics')
    op.drop_index('ix_gpu_metrics_gpu_timestamp', table_name='gpu_metrics')
    op.drop_index(op.f('ix_gpu_metrics_gpu_id'), table_name='gpu_metrics')
    op.drop_table('gpu_metrics')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_server_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_name'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_model_file_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_server_model_directories_server_id'), table_name='server_model_directories')
    op.drop_table('server_model_directories')
    op.drop_index(op.f('ix_server_agents_server_id'), table_name='server_agents')
    op.drop_index(op.f('ix_server_agents_last_seen'), table_name='server_agents')
    op.drop_table('server_agents')
    op.drop_index(op.f('ix_model_files_status'), table_name='model_files')
    op.drop_index(op.f('ix_model_files_server_id'), table_name='model_files')
    op.drop_index(op.f('ix_model_files_model_id'), table_name='model_files')
    op.drop_table('model_files')
    op.drop_index(op.f('ix_model_download_tasks_status'), table_name='model_download_tasks')
    op.drop_index(op.f('ix_model_download_tasks_server_id'), table_name='model_download_tasks')
    op.drop_index(op.f('ix_model_download_tasks_model_id'), table_name='model_download_tasks')
    op.drop_table('model_download_tasks')
    op.drop_index(op.f('ix_gpus_uuid'), table_name='gpus')
    op.drop_index(op.f('ix_gpus_status'), table_name='gpus')
    op.drop_index(op.f('ix_gpus_server_id'), table_name='gpus')
    op.drop_table('gpus')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_servers_status'), table_name='servers')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.drop_index(op.f('ix_servers_last_seen'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_notifications_level'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_model_type'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
